joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

l_wheel_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_wheel_joint
  pid: {p: 10.0, i: 0.01, d: 1.0}

r_wheel_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_wheel_joint
  pid: {p: 10.0, i: 0.01, d: 1.0}
